/* Bacaan sastra & prosedur — Pulau Bahasa Indonesia
   KISAH   fabel dan cerita sekolah: amanat, watak tokoh, sikap teladan
   PUISI   puisi anak karya sendiri: tema, makna larik, perasaan penyair
   PROSEDUR langkah-langkah yang urutannya pasti */
"use strict";

/* Cerita sekolah memakai nama acak: para/tokoh berupa fungsi dari t = { A, B, pak, bu } */
const KISAH = [
  { judul: "Kancil dan Buaya", jenis: "fabel",
    para: [["Kancil ingin menyeberangi sungai untuk mencari makanan di seberang.", "Sayangnya, sungai itu dipenuhi buaya yang sedang lapar."],
      ["Kancil lalu berseru, “Hai, Buaya! Raja hutan memintaku menghitung jumlah kalian. Berbarislah dari tepi ke tepi agar mudah kuhitung!”", "Buaya-buaya itu pun berbaris rapi.", "Kancil melompat di atas punggung mereka sambil berhitung, “Satu, dua, tiga, …”"],
      ["Sesampainya di seberang, Kancil berkata, “Terima kasih, Buaya! Sebenarnya aku hanya ingin menyeberang.”", "Buaya-buaya itu sangat kesal karena tertipu."]],
    amanat: { b: "Gunakanlah akal untuk mengatasi kesulitan.", s: ["Kita harus rajin menabung sejak kecil.", "Kita harus menjaga kebersihan sungai.", "Kita tidak boleh tidur terlalu malam."] },
    tokoh: [{ n: "Kancil", b: "cerdik", s: ["pemalas", "penakut", "pemarah"] }, { n: "buaya-buaya", b: "mudah ditipu", s: ["cerdik", "dermawan", "rajin"] }],
    lanjut: { b: "Kancil mencari makanan di hutan seberang sungai.", s: ["Kancil kembali menyeberang bersama buaya.", "Buaya-buaya berterima kasih kepada Kancil.", "Raja hutan menghitung jumlah buaya."] } },
  { judul: "Semut dan Merpati", jenis: "fabel",
    para: [["Seekor semut terjatuh ke sungai dan hampir tenggelam.", "Seekor merpati yang melihatnya segera menjatuhkan sehelai daun.", "Semut naik ke atas daun itu dan selamat sampai ke tepi."],
      ["Beberapa hari kemudian, seorang pemburu membidik merpati itu dengan ketapel.", "Semut melihatnya dan langsung menggigit kaki si pemburu.", "Pemburu itu kesakitan sehingga bidikannya meleset."],
      ["Merpati pun terbang dengan selamat.", "Sejak itu, semut dan merpati bersahabat."]],
    amanat: { b: "Kebaikan akan dibalas dengan kebaikan.", s: ["Kita harus pandai berenang.", "Kita harus rajin membersihkan rumah.", "Kita harus hemat menggunakan air."] },
    tokoh: [{ n: "merpati", b: "suka menolong", s: ["sombong", "pemarah", "pelit"] }, { n: "semut", b: "tahu membalas budi", s: ["pemalas", "licik", "penakut"] }],
    lanjut: { b: "Semut dan merpati saling menolong ketika salah satunya dalam bahaya.", s: ["Merpati memusuhi semut.", "Semut pindah ke sungai.", "Pemburu menjadi sahabat merpati."] } },
  { judul: "Kelinci dan Kura-Kura", jenis: "fabel",
    para: [["Kelinci selalu membanggakan larinya yang cepat.", "Suatu hari, ia mengejek Kura-kura yang berjalan lambat.", "Kura-kura menjawab dengan tenang, “Bagaimana kalau kita lomba lari?”"],
      ["Lomba pun dimulai.", "Kelinci melesat jauh meninggalkan Kura-kura.", "Karena merasa pasti menang, Kelinci tidur di bawah pohon yang rindang."],
      ["Kura-kura terus berjalan tanpa berhenti.", "Saat Kelinci terbangun, Kura-kura sudah hampir sampai di garis akhir.", "Kelinci berlari sekuat tenaga, tetapi Kura-kura tetap menang."]],
    amanat: { b: "Jangan sombong dan jangan meremehkan orang lain.", s: ["Kita harus rajin berolahraga lari.", "Kita harus tidur siang setiap hari.", "Kita harus menjaga pohon yang rindang."] },
    tokoh: [{ n: "Kelinci", b: "sombong", s: ["rendah hati", "pemaaf", "penolong"] }, { n: "Kura-kura", b: "tekun dan pantang menyerah", s: ["sombong dan pemalas", "licik dan pemarah", "penakut dan cengeng"] }],
    lanjut: { b: "Kelinci menyesal dan tidak lagi mengejek hewan lain.", s: ["Kelinci tidur lagi di bawah pohon.", "Kura-kura mengejek Kelinci setiap hari.", "Kura-kura berhenti berjalan selamanya."] } },
  { judul: "Gagak yang Kehausan", jenis: "fabel",
    para: [["Pada musim kemarau, seekor gagak terbang mencari air.", "Ia sangat haus karena sudah lama tidak minum."],
      ["Akhirnya, gagak menemukan sebuah kendi.", "Sayangnya, air di dalam kendi itu tinggal sedikit di dasar.", "Paruh gagak tidak dapat menjangkaunya."],
      ["Gagak tidak putus asa.", "Ia memungut kerikil satu per satu dan memasukkannya ke dalam kendi.", "Lama-kelamaan, air naik ke atas sehingga gagak dapat minum sepuasnya."]],
    amanat: { b: "Jangan mudah putus asa dan carilah cara untuk mengatasi masalah.", s: ["Kita tidak boleh mengambil barang milik orang lain.", "Kita harus menyimpan air di dalam kendi.", "Kita harus terbang pada musim kemarau."] },
    tokoh: [{ n: "gagak", b: "pantang menyerah dan cerdik", s: ["mudah putus asa", "sombong", "pemalas"] }],
    lanjut: { b: "Gagak terbang kembali dengan segar.", s: ["Gagak memecahkan kendi itu.", "Gagak tetap kehausan.", "Gagak memasukkan air ke dalam kendi."] } },
  { judul: "Semut dan Belalang", jenis: "fabel",
    para: [["Saat musim kemarau, semut bekerja keras mengumpulkan makanan.", "Belalang hanya bernyanyi dan bermain sepanjang hari.", "“Untuk apa bekerja keras? Makanan masih banyak,” kata Belalang."],
      ["Musim hujan pun tiba.", "Makanan di padang rumput sulit ditemukan.", "Belalang kelaparan dan kedinginan."],
      ["Belalang lalu datang ke rumah semut untuk meminta makanan.", "Semut berbagi makanan sambil menasihati Belalang agar lebih rajin.", "Belalang menyesal dan berjanji tidak akan bermalas-malasan lagi."]],
    amanat: { b: "Bersiaplah sejak awal dan jangan bermalas-malasan.", s: ["Kita harus memakai jaket saat musim hujan.", "Kita tidak boleh bermain di padang rumput.", "Kita harus pandai bernyanyi."] },
    tokoh: [{ n: "semut", b: "rajin dan suka berbagi", s: ["pemalas dan pelit", "sombong dan licik", "penakut dan pemarah"] }, { n: "Belalang", b: "pemalas", s: ["rajin", "dermawan", "pemberani"] }],
    lanjut: { b: "Belalang ikut mengumpulkan makanan pada musim kemarau berikutnya.", s: ["Belalang terus bernyanyi sepanjang tahun.", "Semut berhenti mengumpulkan makanan.", "Belalang mengambil makanan semut diam-diam."] } },
  { judul: "Anjing dan Bayangannya", jenis: "fabel",
    para: [["Seekor anjing mendapat sepotong tulang besar dari tukang daging.", "Ia membawa tulang itu pulang sambil menyeberangi jembatan kecil."],
      ["Di bawah jembatan, anjing melihat bayangannya di air.", "Ia mengira bayangan itu anjing lain yang membawa tulang lebih besar.", "Anjing itu ingin merebut tulang tersebut, lalu menggonggong keras."],
      ["Begitu mulutnya terbuka, tulang yang dibawanya jatuh ke sungai.", "Anjing itu pun pulang tanpa membawa apa-apa."]],
    amanat: { b: "Jangan serakah karena dapat merugikan diri sendiri.", s: ["Kita harus berhati-hati saat menyeberangi jembatan.", "Kita harus membeli daging di pasar.", "Kita harus berenang dengan hati-hati."] },
    tokoh: [{ n: "anjing", b: "serakah", s: ["dermawan", "sabar", "rendah hati"] }],
    lanjut: { b: "Anjing menyesal karena kehilangan tulangnya.", s: ["Anjing mendapat dua tulang.", "Anjing lain mengembalikan tulangnya.", "Anjing berenang membawa tulang lebih besar."] } },
  { judul: "Singa dan Tikus", jenis: "fabel",
    para: [["Seekor singa sedang tidur di bawah pohon.", "Tiba-tiba, seekor tikus kecil tanpa sengaja berlari di atas tubuhnya.", "Singa terbangun dan menangkap tikus itu."],
      ["“Ampun, Singa! Lepaskan aku. Suatu hari aku pasti akan membalas kebaikanmu,” kata Tikus.", "Singa tertawa, tetapi akhirnya melepaskan Tikus."],
      ["Beberapa hari kemudian, Singa terjerat jaring pemburu.", "Tikus mendengar aumannya dan segera datang.", "Tikus menggigit tali jaring itu sampai putus sehingga Singa bebas."]],
    amanat: { b: "Jangan meremehkan makhluk yang kecil atau lemah.", s: ["Kita tidak boleh tidur di bawah pohon.", "Kita harus pandai berburu.", "Kita harus berlari dengan cepat."] },
    tokoh: [{ n: "Tikus", b: "menepati janji", s: ["sombong", "pemalas", "licik"] }, { n: "Singa", b: "pemaaf", s: ["pelit", "penakut", "licik"] }],
    lanjut: { b: "Singa dan Tikus menjadi sahabat.", s: ["Singa menangkap Tikus lagi.", "Tikus terjerat jaring pemburu.", "Singa memarahi Tikus."] } },
  { judul: "Dompet di Kantin", jenis: "cerita",
    para: t => [[`Saat jam istirahat, ${t.A} menemukan sebuah dompet di bawah meja kantin.`, `Di dalamnya ada uang dan kartu pelajar milik ${t.B}, kakak kelasnya.`],
      [`Seorang teman berbisik, “Ambil saja uangnya. Tidak ada yang tahu.”`, `${t.A} menggeleng. “Ini bukan milikku,” katanya.`],
      [`${t.A} segera membawa dompet itu ke ruang guru.`, `Bu ${t.bu} memanggil ${t.B} dan menyerahkan dompetnya.`, `${t.B} berterima kasih kepada ${t.A} dengan wajah lega.`]],
    amanat: { b: "Kita harus jujur meskipun tidak ada yang melihat.", s: ["Kita harus sering jajan di kantin.", "Kita harus menyimpan uang di dompet.", "Kita harus berbisik saat berbicara."] },
    tokoh: t => [{ n: t.A, b: "jujur", s: ["serakah", "pemalas", "sombong"] }],
    lanjut: { b: "Teman-teman semakin percaya kepada tokoh yang menemukan dompet.", s: ["Dompet itu hilang lagi.", "Bu guru memarahi semua siswa.", "Kantin sekolah ditutup."] } },
  { judul: "Giliran Piket", jenis: "cerita",
    para: t => [[`Hari itu, ${t.A} mendapat giliran piket kelas bersama ${t.B}.`, `Namun, ${t.A} datang terlambat karena asyik bermain di lapangan.`],
      [`${t.B} membersihkan kelas sendirian.`, `Ia menyapu lantai, menghapus papan tulis, dan merapikan meja.`, `Saat ${t.A} datang, kelas sudah bersih, tetapi ${t.B} tampak sangat lelah.`],
      [`${t.A} merasa bersalah.`, `“Maaf, ${t.B}. Besok aku yang menyapu dan membuang sampah,” katanya.`, `Keesokan harinya, ${t.A} datang paling pagi.`]],
    amanat: { b: "Kita harus bertanggung jawab terhadap tugas kita.", s: ["Kita harus bermain di lapangan setiap pagi.", "Kita harus menghapus papan tulis setelah pulang.", "Kita harus pulang lebih cepat."] },
    tokoh: t => [{ n: t.B, b: "rajin dan bertanggung jawab", s: ["pemalas", "sombong", "ceroboh"] }, { n: t.A, b: "mau mengakui kesalahan", s: ["suka berbohong", "pemarah", "tidak peduli pada teman"] }],
    lanjut: { b: "Mereka membersihkan kelas bersama-sama pada giliran berikutnya.", s: ["Kelas dibiarkan kotor selamanya.", "Mereka bertengkar setiap hari.", "Piket kelas dihapus oleh guru."] } },
  { judul: "Lomba Lari", jenis: "cerita",
    para: t => [[`${t.A} dan ${t.B} mengikuti lomba lari antarkelas.`, `${t.A} adalah pelari tercepat di kelasnya.`],
      [`Saat lomba hampir selesai, ${t.A} berada di posisi pertama.`, `Tiba-tiba, ${t.B} yang berlari di belakangnya terjatuh dan lututnya berdarah.`, `${t.A} berhenti, lalu kembali untuk menolong ${t.B}.`],
      [`Pelari lain menyusul sehingga ${t.A} gagal menjadi juara.`, `Meskipun begitu, teman-teman bertepuk tangan untuknya.`, `“Menolong teman lebih penting daripada piala,” kata ${t.A} sambil tersenyum.`]],
    amanat: { b: "Menolong teman lebih penting daripada mengejar kemenangan.", s: ["Kita harus membeli piala yang bagus.", "Kita harus memakai sepatu baru saat lomba.", "Kita harus berlari di posisi pertama."] },
    tokoh: t => [{ n: t.A, b: "peduli pada teman", s: ["egois", "sombong", "pemalas"] }],
    lanjut: { b: `Persahabatan kedua tokoh menjadi semakin erat.`, s: ["Lomba lari diulang dari awal.", "Teman-teman mengejek tokoh yang kalah.", "Mereka tidak mau berlari lagi."] } },
  { judul: "Pot Bunga yang Pecah", jenis: "cerita",
    para: t => [[`${t.A} bermain bola di halaman sekolah.`, `Tanpa sengaja, bolanya mengenai pot bunga kesayangan Pak ${t.pak} hingga pecah.`],
      ["Tidak ada seorang pun yang melihat kejadian itu.", `${t.A} bisa saja pergi diam-diam, tetapi hatinya tidak tenang.`],
      [`${t.A} lalu menemui Pak ${t.pak} dan mengakui kesalahannya.`, `Pak ${t.pak} tersenyum. “Terima kasih sudah jujur. Ayo, kita tanam lagi bunganya,” katanya.`, "Mereka pun menanam bunga itu di pot yang baru."]],
    amanat: { b: "Beranilah mengakui kesalahan dengan jujur.", s: ["Kita harus membeli pot yang kuat.", "Kita harus menyiram bunga setiap hari.", "Kita tidak boleh menanam bunga di sekolah."] },
    tokoh: t => [{ n: t.A, b: "jujur dan berani bertanggung jawab", s: ["penakut dan suka berbohong", "sombong dan pemarah", "pemalas dan ceroboh"] }, { n: `Pak ${t.pak}`, b: "pemaaf", s: ["pemarah", "pelit", "sombong"] }],
    lanjut: { b: "Tokoh itu lebih berhati-hati saat bermain bola.", s: ["Tokoh itu memecahkan pot lain dengan sengaja.", "Pak guru melarang semua siswa bermain.", "Bunga itu dibuang ke tempat sampah."] } },
  { judul: "Bekal untuk Berdua", jenis: "cerita",
    para: t => [[`${t.A} lupa membawa bekal ke sekolah.`, "Saat jam istirahat, ia hanya duduk diam di kelas sambil menahan lapar."],
      [`${t.B} melihatnya dan duduk di sampingnya.`, `“Ayo makan bersama. Bekalku cukup untuk kita berdua,” kata ${t.B} sambil membuka kotak makannya.`],
      [`${t.A} merasa terharu.`, `Keesokan harinya, ${t.A} membawa dua buah pisang, satu untuk dirinya dan satu untuk ${t.B}.`]],
    amanat: { b: "Berbagilah dengan teman yang membutuhkan.", s: ["Kita harus membawa bekal yang mahal.", "Kita harus makan pisang setiap hari.", "Kita tidak boleh makan di kelas."] },
    tokoh: t => [{ n: t.B, b: "dermawan", s: ["pelit", "sombong", "pemalas"] }, { n: t.A, b: "tahu berterima kasih", s: ["tidak tahu berterima kasih", "pemarah", "sombong"] }],
    lanjut: { b: "Kedua tokoh terbiasa berbagi bekal.", s: ["Kedua tokoh tidak pernah membawa bekal lagi.", "Kedua tokoh bertengkar karena pisang.", "Kedua tokoh makan di kantin sendirian."] } },
];
/* Kisah siap pakai: nama acak untuk cerita sekolah */
function kisahAcak(pakai) {
  const k = pakai || pilih(KISAH), [A, B] = namaBeda(2), t = { A, B, pak: pilih(DEWASA), bu: pilih(DEWASA_BU) };
  return { ...k, para: typeof k.para === "function" ? k.para(t) : k.para, tokoh: typeof k.tokoh === "function" ? k.tokoh(t) : k.tokoh, t };
}

const PUISI = [
  { judul: "Ibu", bait: [["Ibu, kaulah pelita di rumah kami", "Bangun paling pagi, tidur paling akhir", "Tanganmu lembut menyiapkan sarapan", "Doamu menemani langkahku ke sekolah"],
      ["Lelahmu tak pernah kau tunjukkan", "Senyummu selalu kau berikan", "Terima kasih, Ibu tersayang", "Jasamu takkan pernah kulupakan"]],
    tema: { b: "kasih sayang dan jasa ibu", s: ["keindahan alam", "persahabatan", "perjuangan pahlawan"] },
    makna: [{ l: "Ibu, kaulah pelita di rumah kami", b: "ibu menjadi penerang dan penuntun keluarga", s: ["ibu sering menyalakan lampu", "rumah kami selalu gelap", "ibu bekerja di toko lampu"] },
      { l: "Bangun paling pagi, tidur paling akhir", b: "ibu bekerja keras mengurus keluarga", s: ["ibu suka menonton televisi sampai larut", "ibu sulit tidur karena sakit", "ibu suka bangun kesiangan"] }],
    rasa: { b: "sayang dan berterima kasih kepada ibu", s: ["kecewa kepada ibu", "takut kepada ibu", "marah kepada ibu"] },
    larik: [{ q: "Larik yang menunjukkan ibu bekerja keras adalah …", b: "Bangun paling pagi, tidur paling akhir" }, { q: "Larik yang menunjukkan ibu mendoakan anaknya adalah …", b: "Doamu menemani langkahku ke sekolah" }] },
  { judul: "Guruku", bait: [["Setiap pagi kau sambut kami", "Dengan senyum dan sapa yang hangat", "Kau ajari kami membaca dan berhitung", "Dengan sabar tanpa kenal lelah"],
      ["Ilmu darimu bagai cahaya", "Menerangi jalan masa depanku", "Terima kasih, Guruku", "Jasamu terukir di hatiku"]],
    tema: { b: "jasa guru", s: ["keindahan desa", "kasih sayang ayah", "cinta tanah air"] },
    makna: [{ l: "Ilmu darimu bagai cahaya / Menerangi jalan masa depanku", b: "ilmu dari guru membantu meraih masa depan", s: ["guru menyalakan lampu di jalan", "jalan menuju sekolah sangat terang", "guru mengajar pada malam hari"] },
      { l: "Jasamu terukir di hatiku", b: "jasa guru selalu diingat", s: ["guru menulis di dada muridnya", "guru pandai mengukir kayu", "hati penyair sedang sakit"] }],
    rasa: { b: "hormat dan berterima kasih kepada guru", s: ["bosan kepada guru", "takut kepada guru", "iri kepada guru"] },
    larik: [{ q: "Larik yang menunjukkan kesabaran guru adalah …", b: "Dengan sabar tanpa kenal lelah" }, { q: "Larik yang menunjukkan keramahan guru adalah …", b: "Dengan senyum dan sapa yang hangat" }] },
  { judul: "Hujan", bait: [["Rintik hujan mengetuk jendela", "Tik, tik, tik, merdu suaranya", "Sawah kering kini basah", "Petani tersenyum lega"],
      ["Hujan, kau bawa kesejukan", "Bagi bumi yang lama kehausan", "Bunga-bunga kembali bermekaran", "Katak bernyanyi bersahutan"]],
    tema: { b: "manfaat hujan bagi alam", s: ["kesedihan karena banjir", "jasa seorang guru", "persahabatan dua anak"] },
    makna: [{ l: "Bagi bumi yang lama kehausan", b: "tanah sudah lama kering karena tidak turun hujan", s: ["bumi ingin minum air putih", "banyak orang kehausan di jalan", "bumi sedang sakit demam"] },
      { l: "Rintik hujan mengetuk jendela", b: "air hujan jatuh mengenai jendela dan berbunyi", s: ["ada tamu datang mengetuk pintu", "jendela rumah rusak", "hujan ingin masuk ke rumah"] }],
    rasa: { b: "senang dan bersyukur atas turunnya hujan", s: ["takut dan cemas karena banjir", "marah karena tidak bisa bermain", "sedih karena sawah rusak"] },
    larik: [{ q: "Larik yang menunjukkan petani senang karena hujan adalah …", b: "Petani tersenyum lega" }, { q: "Larik yang menunjukkan tumbuhan tumbuh subur kembali adalah …", b: "Bunga-bunga kembali bermekaran" }] },
  { judul: "Sahabat", bait: [["Kau datang saat aku sendiri", "Kau hibur saat aku bersedih", "Tawa kita berpadu di taman bermain", "Bekal pun kita bagi berdua"],
      ["Sahabat, kita bagai dua sayap", "Saling melengkapi saat terbang", "Walau kelak kita berpisah jalan", "Persahabatan kita takkan hilang"]],
    tema: { b: "persahabatan", s: ["cita-cita", "kebersihan lingkungan", "jasa pahlawan"] },
    makna: [{ l: "Sahabat, kita bagai dua sayap / Saling melengkapi saat terbang", b: "sahabat saling membutuhkan dan saling membantu", s: ["penyair dan sahabatnya bisa terbang", "penyair memelihara burung", "sahabat penyair adalah seekor burung"] },
      { l: "Walau kelak kita berpisah jalan", b: "meskipun suatu hari tidak lagi bersama", s: ["mereka tersesat di jalan", "jalan menuju rumah bercabang", "mereka bertengkar di jalan"] }],
    rasa: { b: "bahagia memiliki sahabat", s: ["kesal kepada sahabat", "kesepian tanpa teman", "takut kehilangan bekal"] },
    larik: [{ q: "Larik yang menunjukkan sahabat suka berbagi adalah …", b: "Bekal pun kita bagi berdua" }, { q: "Larik yang menunjukkan sahabat menghibur penyair adalah …", b: "Kau hibur saat aku bersedih" }] },
  { judul: "Pahlawanku", bait: [["Dulu kau angkat senjata", "Melawan penjajah tanpa rasa takut", "Darah dan air mata kau korbankan", "Demi merah putih berkibar"],
      ["Kini tugas kami melanjutkan", "Belajar giat mengisi kemerdekaan", "Takkan kami sia-siakan", "Perjuanganmu, wahai pahlawan"]],
    tema: { b: "perjuangan pahlawan", s: ["keindahan alam", "kasih sayang ibu", "permainan anak-anak"] },
    makna: [{ l: "Demi merah putih berkibar", b: "demi kemerdekaan Indonesia", s: ["agar bendera tidak kusut", "supaya angin bertiup kencang", "untuk menghias tiang bendera"] },
      { l: "Belajar giat mengisi kemerdekaan", b: "anak-anak menghargai perjuangan pahlawan dengan rajin belajar", s: ["anak-anak harus ikut berperang", "anak-anak belajar memakai senjata", "anak-anak berlibur pada hari kemerdekaan"] }],
    rasa: { b: "bangga dan menghormati pahlawan", s: ["takut kepada pahlawan", "kecewa kepada pahlawan", "bosan mendengar kisah pahlawan"] },
    larik: [{ q: "Larik yang menunjukkan keberanian pahlawan adalah …", b: "Melawan penjajah tanpa rasa takut" }, { q: "Larik yang menunjukkan cara anak-anak mengisi kemerdekaan adalah …", b: "Belajar giat mengisi kemerdekaan" }] },
  { judul: "Pohon di Halaman Sekolah", bait: [["Daunmu rimbun menaungi kami", "Saat matahari bersinar terik", "Akarmu kuat mencengkeram bumi", "Menahan tanah agar tak longsor"],
      ["Pohon, kau tak pernah meminta", "Namun memberi udara segar", "Kami berjanji menjagamu", "Tak akan ada yang menebangmu"]],
    tema: { b: "manfaat pohon bagi kehidupan", s: ["persahabatan di sekolah", "perjuangan pahlawan", "kerja keras petani"] },
    makna: [{ l: "Daunmu rimbun menaungi kami", b: "daun pohon yang lebat membuat tempat di bawahnya teduh", s: ["daun pohon sering berjatuhan", "pohon itu menutupi jalan", "daun pohon dimakan ulat"] },
      { l: "Pohon, kau tak pernah meminta / Namun memberi udara segar", b: "pohon memberi manfaat tanpa meminta balasan", s: ["pohon meminta disiram setiap hari", "udara di sekolah sangat panas", "pohon tidak berguna bagi manusia"] }],
    rasa: { b: "sayang dan peduli kepada pohon", s: ["takut kepada pohon", "marah kepada pohon", "kecewa kepada pohon"] },
    larik: [{ q: "Larik yang menunjukkan pohon mencegah tanah longsor adalah …", b: "Menahan tanah agar tak longsor" }, { q: "Larik yang menunjukkan janji untuk menjaga pohon adalah …", b: "Kami berjanji menjagamu" }] },
  { judul: "Indonesiaku", bait: [["Dari Sabang sampai Merauke", "Berjajar pulau-pulau indah", "Gunung menjulang, laut membiru", "Kekayaan alam tiada tara"],
      ["Beragam suku, bahasa, dan budaya", "Bersatu dalam Bhinneka Tunggal Ika", "Aku bangga menjadi anak Indonesia", "Akan kujaga sepanjang masa"]],
    tema: { b: "cinta tanah air", s: ["kasih sayang guru", "manfaat hujan", "persahabatan"] },
    makna: [{ l: "Bersatu dalam Bhinneka Tunggal Ika", b: "meskipun berbeda-beda, tetap bersatu", s: ["semua orang harus sama", "setiap suku hidup sendiri-sendiri", "Indonesia hanya punya satu bahasa daerah"] },
      { l: "Kekayaan alam tiada tara", b: "kekayaan alam Indonesia sangat melimpah", s: ["Indonesia tidak punya kekayaan alam", "harga barang di Indonesia mahal", "alam Indonesia sulit dijangkau"] }],
    rasa: { b: "bangga dan cinta kepada Indonesia", s: ["sedih tinggal di Indonesia", "takut pada laut", "bosan melihat gunung"] },
    larik: [{ q: "Larik yang menunjukkan keragaman Indonesia adalah …", b: "Beragam suku, bahasa, dan budaya" }, { q: "Larik yang menunjukkan luas wilayah Indonesia adalah …", b: "Dari Sabang sampai Merauke" }] },
];
const puisiHtml = p => `<h4>${p.judul}</h4><div class="puisi">${p.bait.map(b => `<p>${b.join("<br>")}</p>`).join("")}</div>`;

const PROSEDUR = [
  { judul: "Cara Mencuci Tangan dengan Sabun", langkah: ["Basahi tangan dengan air mengalir.", "Tuangkan sabun ke telapak tangan.", "Gosok telapak tangan, punggung tangan, dan sela-sela jari.", "Bilas tangan dengan air mengalir sampai bersih.", "Keringkan tangan dengan handuk atau tisu bersih."] },
  { judul: "Cara Menanam Biji Kacang Hijau", langkah: ["Siapkan gelas plastik dan kapas.", "Basahi kapas dengan air, lalu letakkan di dasar gelas.", "Taruh biji kacang hijau di atas kapas.", "Letakkan gelas di tempat yang terkena cahaya matahari.", "Siram kapas setiap hari agar tetap lembap."] },
  { judul: "Cara Membuat Teh Manis", langkah: ["Rebus air hingga mendidih.", "Masukkan kantong teh ke dalam gelas.", "Tuangkan air panas ke dalam gelas.", "Tambahkan gula secukupnya.", "Aduk hingga gula larut."] },
  { judul: "Cara Menggosok Gigi", langkah: ["Basahi sikat gigi dengan air bersih.", "Oleskan pasta gigi sebesar biji jagung pada sikat.", "Sikat seluruh permukaan gigi selama dua menit.", "Berkumur dengan air bersih.", "Bilas sikat gigi, lalu simpan di tempatnya."] },
  { judul: "Cara Meminjam Buku di Perpustakaan", langkah: ["Pilih buku yang ingin dipinjam.", "Bawa buku itu ke meja petugas.", "Serahkan kartu anggota perpustakaan.", "Tunggu petugas mencatat tanggal pinjam dan tanggal kembali.", "Bawa pulang buku dan kembalikan tepat waktu."] },
  { judul: "Cara Membuat Es Jeruk", langkah: ["Cuci jeruk sampai bersih.", "Belah jeruk menjadi dua bagian.", "Peras jeruk ke dalam gelas.", "Tambahkan gula dan air, lalu aduk.", "Masukkan es batu ke dalam gelas."] },
  { judul: "Cara Merebus Telur", langkah: ["Masukkan telur ke dalam panci.", "Tuangkan air hingga telur terendam.", "Rebus di atas api selama sepuluh menit.", "Angkat telur, lalu rendam dalam air dingin.", "Kupas kulit telur."] },
  { judul: "Cara Membuat Pupuk Kompos Sederhana", langkah: ["Kumpulkan daun kering dan sisa sayuran.", "Potong sampah itu kecil-kecil.", "Masukkan potongan sampah ke dalam ember berlubang.", "Tambahkan sedikit tanah, lalu siram dengan air.", "Aduk setiap minggu sampai sampah berubah menjadi kompos."] },
];
