/* Bacaan informasi (nonfiksi) — Pulau Bahasa Indonesia
   Fakta di sini nyata dan dicek dengan sumber umum (buku IPAS SD, situs resmi).
   Setiap bacaan juga membawa:
     ide    ide pokok tiap paragraf { b, s: [pengecoh berupa detail paragraf itu] }
     jd     pengecoh judul (judul yang benar = judul bacaan)
     simpul simpulan { b, s } */
"use strict";

const INFO = [
  { judul: "Komodo, Kadal Raksasa dari Indonesia",
    para: [["Komodo adalah kadal terbesar di dunia.", "Hewan ini hanya hidup di Indonesia, yaitu di Pulau Komodo, Pulau Rinca, dan beberapa pulau kecil di Nusa Tenggara Timur."],
      ["Panjang tubuh komodo dewasa dapat mencapai tiga meter.", "Komodo memakan daging, misalnya rusa dan babi hutan.", "Komodo menjulurkan lidahnya yang bercabang untuk mencium bau mangsa dari jarak jauh."],
      ["Komodo termasuk hewan yang dilindungi.", "Untuk menjaganya, pemerintah mendirikan Taman Nasional Komodo pada tahun 1980."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Di provinsi manakah komodo hidup?", b: "Nusa Tenggara Timur", s: ["Nusa Tenggara Barat", "Sulawesi Selatan", "Bali", "Papua"], pr: v => `Komodo hidup di ${v}.` },
      { p: 0, k: [0, 0], q: "Menurut bacaan, komodo adalah …", b: "kadal terbesar di dunia", s: ["ular terpanjang di dunia", "buaya terbesar di Asia", "kadal terkecil di dunia"], pr: v => `Komodo adalah ${v}.` },
      { p: 1, k: [1, 0], q: "Panjang tubuh komodo dewasa dapat mencapai …", b: "tiga meter", s: ["satu meter", "lima meter", "sepuluh meter"], pr: v => `Panjang komodo dewasa dapat mencapai ${v}.` },
      { p: 1, k: [1, 1], q: "Apa makanan komodo?", b: "daging, misalnya rusa dan babi hutan", s: ["buah-buahan dan dedaunan", "ikan dan rumput laut", "serangga dan biji-bijian"], pr: v => `Komodo memakan ${v}.` },
      { p: 1, k: [1, 2], q: "Untuk apa komodo menjulurkan lidahnya?", b: "untuk mencium bau mangsa", s: ["untuk meminum air", "untuk mengusir lalat", "untuk mendinginkan tubuh"], pr: v => `Komodo menjulurkan lidahnya ${v}.`, sulit: true },
      { p: 2, k: [2, 1], q: "Taman Nasional Komodo didirikan pada tahun …", b: "1980", s: ["1945", "1970", "1990", "2000"], pr: v => `Taman Nasional Komodo didirikan pada tahun ${v}.`, sulit: true },
    ],
    ide: [{ b: "komodo sebagai kadal terbesar yang hanya hidup di Indonesia", s: ["Pulau Rinca di Nusa Tenggara Timur", "pulau-pulau kecil di Indonesia", "jumlah kadal di dunia"] },
      { b: "ciri-ciri dan makanan komodo", s: ["rusa dan babi hutan", "lidah komodo yang bercabang", "bau mangsa dari jarak jauh"] },
      { b: "upaya melindungi komodo", s: ["tahun 1980", "pemerintah Indonesia", "taman di kota"] }],
    jd: ["Rusa dan Babi Hutan", "Liburan ke Pulau Bali", "Cara Merawat Kadal di Rumah"],
    simpul: { b: "Komodo adalah hewan langka khas Indonesia yang perlu dilindungi.", s: ["Komodo dapat ditemukan di seluruh pulau di Indonesia.", "Komodo adalah hewan pemakan tumbuhan.", "Komodo cocok dipelihara di rumah."] } },

  { judul: "Orangutan, Penghuni Hutan Hujan",
    para: [["Orangutan adalah kera besar berbulu cokelat kemerahan.", "Di Indonesia, orangutan hanya hidup di hutan hujan Pulau Sumatra dan Pulau Kalimantan."],
      ["Orangutan menghabiskan sebagian besar waktunya di atas pohon.", "Makanan utamanya adalah buah-buahan, misalnya durian dan buah ara.", "Setiap sore, orangutan membuat sarang dari ranting dan daun untuk tidur.", "Anak orangutan tinggal bersama induknya selama enam sampai delapan tahun."],
      ["Sayangnya, orangutan kini terancam punah.", "Hutan tempat tinggalnya banyak ditebang dan terbakar.", "Karena itu, kita perlu menjaga hutan agar orangutan tetap lestari."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Apa warna bulu orangutan?", b: "cokelat kemerahan", s: ["hitam pekat", "putih keabu-abuan", "kuning keemasan"], pr: v => `Bulu orangutan berwarna ${v}.` },
      { p: 0, k: [0, 1], q: "Di Indonesia, orangutan hidup di …", b: "hutan hujan Sumatra dan Kalimantan", s: ["hutan bakau Jawa dan Bali", "padang rumput Nusa Tenggara", "hutan pinus Sulawesi dan Papua"], pr: v => `Di Indonesia, orangutan hidup di ${v}.` },
      { p: 1, k: [1, 1], q: "Apa makanan utama orangutan?", b: "buah-buahan", s: ["daging rusa", "ikan sungai", "rumput kering"], pr: v => `Makanan utama orangutan adalah ${v}.` },
      { p: 1, k: [1, 2], q: "Orangutan membuat sarang dari …", b: "ranting dan daun", s: ["lumpur dan batu", "rumput kering dan bulu", "tanah liat dan jerami"], pr: v => `Orangutan membuat sarang dari ${v}.` },
      { p: 1, k: [1, 2], q: "Kapan orangutan membuat sarang untuk tidur?", b: "setiap sore", s: ["setiap pagi", "seminggu sekali", "hanya saat hujan"], pr: v => `Orangutan membuat sarang untuk tidur ${v}.`, sulit: true },
      { p: 1, k: [1, 3], q: "Berapa lama anak orangutan tinggal bersama induknya?", b: "enam sampai delapan tahun", s: ["satu sampai dua tahun", "tiga bulan", "sepuluh sampai dua belas tahun"], pr: v => `Anak orangutan tinggal bersama induknya selama ${v}.`, sulit: true },
      { p: 2, k: [2, 1], q: "Mengapa orangutan terancam punah?", b: "hutan tempat tinggalnya banyak ditebang dan terbakar", s: ["orangutan tidak bisa memanjat pohon", "makanan orangutan terlalu banyak", "orangutan suka tinggal di kota"], pr: v => `Orangutan terancam punah karena ${v}.`, sulit: true },
    ],
    ide: [{ b: "ciri dan tempat hidup orangutan", s: ["warna bulu kera di Afrika", "hutan hujan di Pulau Jawa", "jumlah pulau di Indonesia"] },
      { b: "kebiasaan hidup orangutan", s: ["durian dan buah ara", "ranting dan daun untuk sarang", "umur anak orangutan"] },
      { b: "orangutan terancam punah sehingga hutan perlu dijaga", s: ["hutan yang terbakar", "penebangan pohon untuk rumah", "orangutan yang lestari"] }],
    jd: ["Durian, Buah Kesukaan Kita", "Kebun Binatang di Kota", "Cara Menanam Pohon Ara"],
    simpul: { b: "Orangutan adalah hewan pohon yang perlu dilindungi dengan menjaga hutan.", s: ["Orangutan dapat hidup dengan baik tanpa hutan.", "Orangutan adalah hewan pemakan daging.", "Orangutan hidup di semua pulau di Indonesia."] } },

  { judul: "Perjalanan Hidup Penyu",
    para: [["Penyu adalah hewan laut yang bertelur di darat.", "Penyu betina naik ke pantai pada malam hari untuk bertelur."],
      ["Dengan sirip belakangnya, penyu menggali lubang di pasir.", "Di lubang itu, penyu bertelur hingga lebih dari seratus butir.", "Setelah lubang ditutup kembali dengan pasir, penyu pulang ke laut.", "Sekitar dua bulan kemudian, telur-telur itu menetas."],
      ["Anak penyu disebut tukik.", "Tukik yang baru menetas langsung berjalan menuju laut.", "Dalam perjalanannya, tukik menghadapi banyak bahaya, misalnya dimangsa burung dan kepiting.", "Karena itu, hanya sedikit tukik yang dapat tumbuh menjadi penyu dewasa."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Di mana penyu bertelur?", b: "di pantai", s: ["di dasar laut", "di atas batu karang", "di tepi sungai"], pr: v => `Penyu bertelur ${v}.` },
      { p: 0, k: [0, 1], q: "Kapan penyu betina naik ke pantai untuk bertelur?", b: "pada malam hari", s: ["pada pagi hari", "pada siang hari", "saat hujan deras"], pr: v => `Penyu betina naik ke pantai ${v}.` },
      { p: 1, k: [1, 0], q: "Penyu menggali lubang dengan …", b: "sirip belakangnya", s: ["paruhnya", "sirip depannya", "tempurungnya"], pr: v => `Penyu menggali lubang dengan ${v}.`, sulit: true },
      { p: 1, k: [1, 1], q: "Banyak telur penyu dalam satu lubang dapat mencapai …", b: "lebih dari seratus butir", s: ["sepuluh butir", "dua puluh butir", "lima butir"], pr: v => `Penyu dapat bertelur ${v}.` },
      { p: 1, k: [1, 3], q: "Telur penyu menetas setelah …", b: "sekitar dua bulan", s: ["sekitar dua hari", "sekitar satu tahun", "sekitar dua minggu"], pr: v => `Telur penyu menetas setelah ${v}.` },
      { p: 2, k: [2, 0], q: "Anak penyu disebut …", b: "tukik", s: ["berudu", "cempe", "larva"], pr: v => `Anak penyu disebut ${v}.` },
      { p: 2, k: [2, 2], q: "Menurut bacaan, hewan apa yang memangsa tukik?", b: "burung dan kepiting", s: ["ular dan katak", "kucing dan anjing", "ikan hiu dan paus"], pr: v => `Tukik dapat dimangsa ${v}.`, sulit: true },
    ],
    ide: [{ b: "penyu bertelur di darat", s: ["penyu betina yang berenang", "pantai pada malam hari", "makanan penyu di laut"] },
      { b: "cara penyu bertelur", s: ["lubang di pasir pantai", "sirip belakang penyu", "lamanya telur menetas"] },
      { b: "kehidupan tukik yang penuh bahaya", s: ["burung dan kepiting di pantai", "penyu dewasa di laut", "jumlah telur penyu"] }],
    jd: ["Bermain Pasir di Pantai", "Kepiting yang Lucu", "Membuat Istana Pasir"],
    simpul: { b: "Penyu bertelur di darat, tetapi tukiknya harus berjuang keras untuk bertahan hidup.", s: ["Semua tukik pasti tumbuh menjadi penyu dewasa.", "Penyu bertelur di dasar laut.", "Penyu hanya bertelur satu butir setiap kali."] } },

  { judul: "Kehidupan Lebah Madu",
    para: [["Lebah madu hidup berkelompok di dalam sarang.", "Satu sarang dapat dihuni puluhan ribu lebah."],
      ["Dalam satu kelompok terdapat ratu lebah, lebah pekerja, dan lebah jantan.", "Ratu lebah bertugas bertelur.", "Lebah pekerja mencari makanan, membersihkan sarang, dan menjaga sarang dari musuh.", "Jumlah lebah pekerja paling banyak di antara lebah lainnya."],
      ["Lebah pekerja mengisap nektar dari bunga.", "Nektar itu diolah di dalam tubuhnya, lalu disimpan di sarang hingga menjadi madu.", "Saat berpindah dari bunga ke bunga, lebah juga membawa serbuk sari sehingga membantu penyerbukan."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Bagaimana lebah madu hidup?", b: "berkelompok di dalam sarang", s: ["sendiri-sendiri di dalam tanah", "berpasangan di dalam gua", "berpindah-pindah tanpa sarang"], pr: v => `Lebah madu hidup ${v}.` },
      { p: 0, k: [0, 1], q: "Satu sarang lebah dapat dihuni …", b: "puluhan ribu lebah", s: ["puluhan lebah", "ratusan lebah", "sepuluh lebah"], pr: v => `Satu sarang dapat dihuni ${v}.` },
      { p: 1, k: [1, 1], q: "Apa tugas ratu lebah?", b: "bertelur", s: ["mencari makanan", "menjaga sarang", "membersihkan sarang"], pr: v => `Tugas ratu lebah adalah ${v}.` },
      { p: 1, k: [1, 3], q: "Lebah yang jumlahnya paling banyak di sarang adalah …", b: "lebah pekerja", s: ["ratu lebah", "lebah jantan", "lebah penjaga bunga"], pr: v => `Jumlah ${v} paling banyak di dalam sarang.`, sulit: true },
      { p: 2, k: [2, 0], q: "Lebah pekerja mengisap … dari bunga.", b: "nektar", s: ["getah", "air hujan", "daun muda"], pr: v => `Lebah pekerja mengisap ${v} dari bunga.` },
      { p: 2, k: [2, 2], q: "Mengapa lebah dapat membantu penyerbukan?", b: "lebah membawa serbuk sari dari bunga ke bunga", s: ["lebah membuat sarang di dekat bunga", "lebah memakan daun tumbuhan", "lebah menyiram bunga dengan madu"], pr: v => `Lebah membantu penyerbukan karena ${v}.`, sulit: true },
    ],
    ide: [{ b: "lebah madu hidup berkelompok", s: ["sarang lebah di pohon", "puluhan ribu sarang", "madu yang manis"] },
      { b: "pembagian tugas dalam kelompok lebah", s: ["ratu lebah yang bertelur", "musuh lebah di sekitar sarang", "jumlah lebah jantan"] },
      { b: "kegiatan lebah pekerja di bunga", s: ["warna bunga yang disukai lebah", "serbuk sari pada bunga", "sarang tempat menyimpan madu"] }],
    jd: ["Manisnya Gula Aren", "Bunga di Taman Sekolah", "Cara Memasak dengan Madu"],
    simpul: { b: "Lebah madu bekerja sama dalam kelompok dan bermanfaat bagi manusia serta tumbuhan.", s: ["Lebah madu selalu hidup sendiri.", "Semua lebah di sarang bertugas bertelur.", "Lebah merusak bunga yang dihinggapinya."] } },

  { judul: "Metamorfosis Kupu-Kupu",
    para: [["Kupu-kupu mengalami perubahan bentuk selama hidupnya.", "Perubahan bentuk itu disebut metamorfosis sempurna."],
      ["Mula-mula, kupu-kupu betina bertelur di permukaan daun.", "Telur itu menetas menjadi ulat.", "Ulat makan daun sangat banyak sehingga tubuhnya cepat besar."],
      ["Setelah cukup besar, ulat membungkus dirinya dan menjadi kepompong.", "Di dalam kepompong, tubuhnya berubah bentuk.", "Beberapa hari kemudian, kepompong terbuka dan keluarlah kupu-kupu dewasa yang bersayap indah."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Perubahan bentuk kupu-kupu disebut …", b: "metamorfosis sempurna", s: ["metamorfosis tidak sempurna", "fotosintesis", "penyerbukan"], pr: v => `Perubahan bentuk kupu-kupu disebut ${v}.` },
      { p: 1, k: [1, 0], q: "Kupu-kupu betina bertelur di …", b: "permukaan daun", s: ["dalam tanah", "batang pohon", "dalam air"], pr: v => `Kupu-kupu betina bertelur di ${v}.` },
      { p: 1, k: [1, 1], q: "Telur kupu-kupu menetas menjadi …", b: "ulat", s: ["kepompong", "berudu", "kupu-kupu kecil"], pr: v => `Telur kupu-kupu menetas menjadi ${v}.` },
      { p: 1, k: [1, 2], q: "Mengapa tubuh ulat cepat besar?", b: "ulat makan daun sangat banyak", s: ["ulat banyak tidur", "ulat minum banyak air", "ulat tinggal di kepompong"], pr: v => `Tubuh ulat cepat besar karena ${v}.`, sulit: true },
      { p: 2, k: [2, 0], q: "Ulat yang membungkus dirinya akan menjadi …", b: "kepompong", s: ["telur", "kupu-kupu betina", "sarang"], pr: v => `Ulat yang membungkus dirinya menjadi ${v}.` },
      { p: 2, k: [2, 2], q: "Urutan metamorfosis kupu-kupu menurut bacaan adalah …", b: "telur → ulat → kepompong → kupu-kupu", s: ["telur → kepompong → ulat → kupu-kupu", "ulat → telur → kepompong → kupu-kupu", "kepompong → telur → ulat → kupu-kupu"], pr: v => `Urutan metamorfosis kupu-kupu adalah ${v}.`, sulit: true },
    ],
    ide: [{ b: "kupu-kupu mengalami metamorfosis sempurna", s: ["sayap kupu-kupu yang indah", "telur kupu-kupu", "makanan ulat"] },
      { b: "tahap telur dan ulat", s: ["daun yang dimakan ulat", "kupu-kupu betina", "tubuh ulat yang besar"] },
      { b: "tahap kepompong hingga menjadi kupu-kupu", s: ["sayap yang indah", "bungkus ulat", "beberapa hari kemudian"] }],
    jd: ["Ulat Pemakan Daun Jagung", "Taman Bunga yang Indah", "Serangga Pengganggu Tanaman"],
    simpul: { b: "Kupu-kupu melewati tahap telur, ulat, dan kepompong sebelum menjadi kupu-kupu dewasa.", s: ["Kupu-kupu lahir langsung bersayap.", "Ulat tidak pernah berubah bentuk.", "Kepompong menetas menjadi ulat."] } },

  { judul: "Hutan Mangrove, Penjaga Pantai",
    para: [["Hutan mangrove disebut juga hutan bakau.", "Hutan ini tumbuh di pantai berlumpur, tempat air laut dan air sungai bertemu."],
      ["Akar mangrove mencuat ke atas permukaan lumpur dan saling berkaitan.", "Akar yang kuat itu menahan tanah pantai agar tidak terkikis ombak.", "Pengikisan pantai oleh ombak disebut abrasi."],
      ["Hutan mangrove juga menjadi rumah bagi banyak hewan, seperti ikan, kepiting, udang, dan burung.", "Oleh karena itu, hutan mangrove tidak boleh ditebang sembarangan."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Hutan mangrove disebut juga …", b: "hutan bakau", s: ["hutan pinus", "hutan jati", "hutan hujan"], pr: v => `Hutan mangrove disebut juga ${v}.` },
      { p: 0, k: [0, 1], q: "Di mana hutan mangrove tumbuh?", b: "di pantai berlumpur", s: ["di puncak gunung", "di padang pasir", "di lereng bukit"], pr: v => `Hutan mangrove tumbuh ${v}.` },
      { p: 1, k: [1, 1], q: "Apa fungsi akar mangrove menurut bacaan?", b: "menahan tanah pantai agar tidak terkikis ombak", s: ["menyimpan air hujan", "menjadi makanan ikan", "menambah jumlah lumpur"], pr: v => `Akar mangrove berfungsi ${v}.`, sulit: true },
      { p: 1, k: [1, 2], q: "Apa yang dimaksud dengan abrasi?", b: "pengikisan pantai oleh ombak", s: ["banjir di sungai", "longsor di gunung", "penebangan hutan"], pr: v => `Abrasi adalah ${v}.` },
      { p: 1, k: [1, 0], q: "Bagaimana bentuk akar mangrove?", b: "mencuat ke atas lumpur dan saling berkaitan", s: ["tumbuh lurus ke dalam batu", "menggantung dari dahan tinggi", "kecil dan tersembunyi di pasir"], pr: v => `Akar mangrove ${v}.`, sulit: true },
      { p: 2, k: [2, 0], q: "Hewan apa saja yang tinggal di hutan mangrove?", b: "ikan, kepiting, udang, dan burung", s: ["harimau, gajah, dan rusa", "unta, kuda, dan sapi", "kanguru dan koala"], pr: v => `Hutan mangrove menjadi rumah bagi ${v}.` },
    ],
    ide: [{ b: "pengertian dan tempat tumbuh hutan mangrove", s: ["air sungai yang mengalir ke laut", "lumpur di pantai", "nama-nama pohon bakau"] },
      { b: "akar mangrove mencegah abrasi", s: ["ombak di pantai", "permukaan lumpur", "tanah di pegunungan"] },
      { b: "hutan mangrove sebagai tempat tinggal hewan", s: ["kepiting dan udang", "penebangan pohon jati", "burung di sawah"] }],
    jd: ["Menangkap Kepiting di Sungai", "Liburan ke Puncak Gunung", "Ombak yang Tinggi"],
    simpul: { b: "Hutan mangrove penting untuk menjaga pantai dan tempat hidup hewan sehingga harus dilestarikan.", s: ["Hutan mangrove tumbuh di puncak gunung.", "Hutan mangrove sebaiknya ditebang agar pantai luas.", "Akar mangrove menyebabkan abrasi."] } },

  { judul: "Borobudur, Candi Kebanggaan Indonesia",
    para: [["Candi Borobudur terletak di Magelang, Jawa Tengah.", "Candi ini merupakan candi Buddha terbesar di dunia."],
      ["Borobudur dibangun sekitar abad ke-8 sampai ke-9 pada masa Wangsa Syailendra.", "Candi ini tersusun dari batu andesit.", "Dindingnya dihiasi lebih dari dua ribu panel relief yang menceritakan berbagai kisah."],
      ["Di bagian paling atas terdapat 72 stupa berlubang yang mengelilingi satu stupa induk.", "Pada tahun 1991, UNESCO menetapkan Borobudur sebagai Warisan Dunia.", "Setiap tahun, candi ini dikunjungi banyak wisatawan dari dalam dan luar negeri."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Di manakah Candi Borobudur terletak?", b: "di Magelang, Jawa Tengah", s: ["di Bantul, Yogyakarta", "di Malang, Jawa Timur", "di Bogor, Jawa Barat"], pr: v => `Candi Borobudur terletak ${v}.` },
      { p: 0, k: [0, 1], q: "Menurut bacaan, Borobudur merupakan …", b: "candi Buddha terbesar di dunia", s: ["candi Hindu terbesar di dunia", "candi tertua di Asia", "candi terkecil di Jawa"], pr: v => `Borobudur merupakan ${v}.` },
      { p: 1, k: [1, 0], q: "Borobudur dibangun pada masa …", b: "Wangsa Syailendra", s: ["Kerajaan Majapahit", "Kerajaan Sriwijaya", "Kerajaan Singasari"], pr: v => `Borobudur dibangun pada masa ${v}.` },
      { p: 1, k: [1, 1], q: "Candi Borobudur tersusun dari …", b: "batu andesit", s: ["batu bata merah", "kayu jati", "batu kapur"], pr: v => `Candi Borobudur tersusun dari ${v}.` },
      { p: 2, k: [2, 0], q: "Berapa jumlah stupa berlubang di bagian paling atas Borobudur?", b: "72", s: ["27", "52", "100"], pr: v => `Di bagian paling atas Borobudur terdapat ${v} stupa berlubang.`, sulit: true },
      { p: 2, k: [2, 1], q: "Pada tahun berapa UNESCO menetapkan Borobudur sebagai Warisan Dunia?", b: "1991", s: ["1945", "1981", "2001"], pr: v => `UNESCO menetapkan Borobudur sebagai Warisan Dunia pada tahun ${v}.`, sulit: true },
    ],
    ide: [{ b: "letak dan keistimewaan Candi Borobudur", s: ["Kota Magelang di Jawa Tengah", "agama Buddha di dunia", "candi-candi kecil di Jawa"] },
      { b: "sejarah pembangunan dan bahan Borobudur", s: ["batu andesit dari gunung", "kisah-kisah pada relief", "abad ke-8"] },
      { b: "bagian atas Borobudur dan pengakuan dunia", s: ["stupa induk", "wisatawan luar negeri", "tahun 1991"] }],
    jd: ["Liburan ke Pantai Kuta", "Batu Andesit dari Gunung", "Membuat Relief dari Tanah Liat"],
    simpul: { b: "Borobudur adalah candi bersejarah yang diakui dunia dan perlu dijaga.", s: ["Borobudur adalah candi Hindu kecil di Jawa Timur.", "Borobudur baru dibangun pada tahun 1991.", "Borobudur jarang dikunjungi wisatawan."] } },

  { judul: "Batik, Warisan Budaya Indonesia",
    para: [["Batik adalah kain bergambar yang dibuat dengan cara khusus.", "Gambar pada kain batik dibuat dengan menorehkan malam, yaitu lilin panas, ke atas kain."],
      ["Alat untuk menorehkan malam disebut canting.", "Batik yang dibuat dengan canting disebut batik tulis.", "Ada pula batik cap yang dibuat dengan cap dari tembaga sehingga lebih cepat selesai."],
      ["Pada tanggal 2 Oktober 2009, UNESCO mengakui batik sebagai warisan budaya dunia dari Indonesia.", "Sejak itu, setiap tanggal 2 Oktober diperingati sebagai Hari Batik Nasional.", "Setiap daerah memiliki motif batik khas, misalnya motif mega mendung dari Cirebon."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Apa yang dimaksud dengan malam dalam bacaan?", b: "lilin panas", s: ["cat air", "tinta hitam", "lem kayu"], pr: v => `Malam adalah ${v}.` },
      { p: 0, k: [0, 0], q: "Batik adalah …", b: "kain bergambar yang dibuat dengan cara khusus", s: ["kain polos tanpa gambar", "pakaian dari daun kering", "kertas bergambar untuk hiasan"], pr: v => `Batik adalah ${v}.` },
      { p: 1, k: [1, 0], q: "Alat untuk menorehkan malam disebut …", b: "canting", s: ["kuas", "jarum", "cap"], pr: v => `Alat untuk menorehkan malam disebut ${v}.` },
      { p: 1, k: [1, 2], q: "Apa kelebihan batik cap menurut bacaan?", b: "lebih cepat selesai dibuat", s: ["dibuat dengan canting", "memakai lilin dingin", "tidak memerlukan kain"], pr: v => `Kelebihan batik cap adalah ${v}.`, sulit: true },
      { p: 2, k: [2, 1], q: "Hari Batik Nasional diperingati setiap tanggal …", b: "2 Oktober", s: ["21 April", "17 Agustus", "28 Oktober"], pr: v => `Hari Batik Nasional diperingati setiap tanggal ${v}.` },
      { p: 2, k: [2, 2], q: "Motif mega mendung berasal dari …", b: "Cirebon", s: ["Solo", "Yogyakarta", "Madura"], pr: v => `Motif mega mendung berasal dari ${v}.`, sulit: true },
    ],
    ide: [{ b: "pengertian batik dan cara membuatnya", s: ["lilin panas", "kain putih", "gambar pada kain"] },
      { b: "jenis batik berdasarkan alat pembuatnya", s: ["cap dari tembaga", "canting untuk malam", "batik yang cepat selesai"] },
      { b: "pengakuan dunia terhadap batik", s: ["motif mega mendung", "tanggal 2 Oktober 2009", "daerah-daerah di Indonesia"] }],
    jd: ["Cara Mencuci Pakaian", "Lilin untuk Ulang Tahun", "Pasar Kain di Kota"],
    simpul: { b: "Batik adalah karya budaya Indonesia yang dibuat dengan malam dan diakui dunia.", s: ["Batik hanya dibuat di satu daerah saja.", "Batik dibuat dengan cat semprot.", "Hari Batik Nasional diperingati setiap 17 Agustus."] } },

  { judul: "Angklung, Alat Musik Bambu",
    para: [["Angklung adalah alat musik tradisional dari Jawa Barat.", "Alat musik ini terbuat dari tabung-tabung bambu."],
      ["Angklung dimainkan dengan cara digoyangkan.", "Setiap angklung hanya menghasilkan satu nada.", "Karena itu, sebuah lagu dimainkan oleh banyak orang secara bersama-sama."],
      ["Pada tahun 1938, Daeng Soetigna membuat angklung bernada diatonis sehingga angklung dapat memainkan lagu-lagu modern.", "Pada bulan November 2010, UNESCO menetapkan angklung sebagai warisan budaya dunia dari Indonesia."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Angklung berasal dari …", b: "Jawa Barat", s: ["Jawa Timur", "Bali", "Sumatra Barat"], pr: v => `Angklung berasal dari ${v}.` },
      { p: 0, k: [0, 1], q: "Angklung terbuat dari …", b: "bambu", s: ["kayu jati", "logam", "kulit kambing"], pr: v => `Angklung terbuat dari ${v}.` },
      { p: 1, k: [1, 0], q: "Bagaimana cara memainkan angklung?", b: "digoyangkan", s: ["dipukul", "ditiup", "dipetik"], pr: v => `Angklung dimainkan dengan cara ${v}.` },
      { p: 1, k: [1, 2], q: "Mengapa sebuah lagu angklung dimainkan oleh banyak orang?", b: "setiap angklung hanya menghasilkan satu nada", s: ["angklung sangat berat", "angklung mudah rusak", "angklung hanya boleh dimainkan di sekolah"], pr: v => `Lagu angklung dimainkan banyak orang karena ${v}.`, sulit: true },
      { p: 2, k: [2, 0], q: "Siapa yang membuat angklung bernada diatonis?", b: "Daeng Soetigna", s: ["Ki Hajar Dewantara", "W.R. Supratman", "Ismail Marzuki"], pr: v => `Angklung bernada diatonis dibuat oleh ${v}.` },
      { p: 2, k: [2, 1], q: "Kapan UNESCO menetapkan angklung sebagai warisan budaya dunia?", b: "November 2010", s: ["Oktober 2009", "Agustus 1945", "Januari 2020"], pr: v => `UNESCO menetapkan angklung sebagai warisan budaya dunia pada ${v}.`, sulit: true },
    ],
    ide: [{ b: "asal dan bahan angklung", s: ["tabung-tabung bambu", "musik tradisional Jawa", "hutan bambu di Jawa Barat"] },
      { b: "cara memainkan angklung", s: ["satu nada pada angklung", "lagu yang dimainkan", "banyak orang di panggung"] },
      { b: "perkembangan angklung hingga diakui dunia", s: ["tahun 1938", "lagu-lagu modern", "bulan November"] }],
    jd: ["Menanam Pohon Bambu", "Lagu-Lagu Modern", "Rumah Adat Jawa Barat"],
    simpul: { b: "Angklung adalah alat musik bambu dari Jawa Barat yang dimainkan bersama-sama dan diakui dunia.", s: ["Angklung dimainkan dengan cara ditiup.", "Satu angklung dapat memainkan semua nada lagu.", "Angklung berasal dari Papua."] } },

  { judul: "Siklus Air",
    para: [["Air di bumi selalu bergerak dalam sebuah putaran.", "Putaran itu disebut siklus air."],
      ["Panas matahari membuat air di laut, sungai, dan danau menguap.", "Uap air naik ke udara yang dingin, lalu berubah menjadi titik-titik air.", "Titik-titik air itu berkumpul membentuk awan.", "Peristiwa berubahnya uap air menjadi titik-titik air disebut pengembunan."],
      ["Ketika awan semakin berat, titik-titik air jatuh ke bumi sebagai hujan.", "Air hujan meresap ke dalam tanah atau mengalir melalui sungai menuju laut.", "Setelah itu, air kembali menguap dan siklus pun berulang."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Putaran air di bumi disebut …", b: "siklus air", s: ["siklus hidup", "arus laut", "musim hujan"], pr: v => `Putaran air di bumi disebut ${v}.` },
      { p: 1, k: [1, 0], q: "Apa yang membuat air di laut menguap?", b: "panas matahari", s: ["angin kencang", "cahaya bulan", "ikan di laut"], pr: v => `Air laut menguap karena ${v}.` },
      { p: 1, k: [1, 3], q: "Berubahnya uap air menjadi titik-titik air disebut …", b: "pengembunan", s: ["penguapan", "peresapan", "pembekuan"], pr: v => `Berubahnya uap air menjadi titik-titik air disebut ${v}.`, sulit: true },
      { p: 1, k: [1, 2], q: "Awan terbentuk dari …", b: "titik-titik air yang berkumpul", s: ["asap kendaraan", "debu dari jalan", "uap dari gunung api"], pr: v => `Awan terbentuk dari ${v}.` },
      { p: 2, k: [2, 0], q: "Kapan titik-titik air jatuh sebagai hujan?", b: "ketika awan semakin berat", s: ["ketika matahari bersinar terik", "ketika angin berhenti bertiup", "ketika laut surut"], pr: v => `Hujan turun ${v}.`, sulit: true },
      { p: 2, k: [2, 1], q: "Ke mana air hujan mengalir melalui sungai?", b: "menuju laut", s: ["menuju gunung", "menuju awan", "menuju gua"], pr: v => `Air hujan mengalir melalui sungai ${v}.` },
    ],
    ide: [{ b: "pengertian siklus air", s: ["air di dalam sumur", "putaran roda", "air yang diam"] },
      { b: "proses penguapan sampai terbentuknya awan", s: ["air di danau", "udara yang dingin", "titik-titik air"] },
      { b: "turunnya hujan dan kembalinya air ke laut", s: ["awan yang berat", "air di dalam tanah", "sungai yang panjang"] }],
    jd: ["Bermain Hujan-Hujanan", "Matahari yang Terik", "Laut yang Biru"],
    simpul: { b: "Air di bumi terus berputar melalui penguapan, pengembunan, dan hujan.", s: ["Air hujan tidak pernah kembali ke laut.", "Awan terbentuk dari asap.", "Air hanya menguap pada malam hari."] } },

  { judul: "Cara Tumbuhan Membuat Makanan",
    para: [["Tumbuhan hijau dapat membuat makanannya sendiri.", "Cara tumbuhan membuat makanan disebut fotosintesis."],
      ["Fotosintesis terjadi di daun karena daun mengandung zat hijau daun atau klorofil.", "Untuk berfotosintesis, tumbuhan memerlukan air, karbon dioksida, dan cahaya matahari.", "Air diserap oleh akar dari dalam tanah, sedangkan karbon dioksida diambil dari udara melalui daun."],
      ["Hasil fotosintesis adalah zat gula sebagai makanan dan oksigen.", "Oksigen dilepaskan ke udara dan kita hirup saat bernapas.", "Itulah sebabnya tumbuhan sangat penting bagi kehidupan."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Cara tumbuhan membuat makanan disebut …", b: "fotosintesis", s: ["penyerbukan", "metamorfosis", "penguapan"], pr: v => `Cara tumbuhan membuat makanan disebut ${v}.` },
      { p: 1, k: [1, 0], q: "Di bagian tumbuhan manakah fotosintesis terjadi?", b: "daun", s: ["akar", "batang", "bunga"], pr: v => `Fotosintesis terjadi di ${v}.` },
      { p: 1, k: [1, 0], q: "Zat hijau daun disebut juga …", b: "klorofil", s: ["nektar", "serbuk sari", "getah"], pr: v => `Zat hijau daun disebut juga ${v}.` },
      { p: 1, k: [1, 1], q: "Apa saja yang diperlukan tumbuhan untuk berfotosintesis?", b: "air, karbon dioksida, dan cahaya matahari", s: ["oksigen, gula, dan tanah", "pupuk, pasir, dan angin", "air, oksigen, dan cahaya bulan"], pr: v => `Untuk berfotosintesis, tumbuhan memerlukan ${v}.`, sulit: true },
      { p: 1, k: [1, 2], q: "Air diserap oleh … dari dalam tanah.", b: "akar", s: ["daun", "bunga", "buah"], pr: v => `Air diserap oleh ${v} dari dalam tanah.` },
      { p: 2, k: [2, 0], q: "Apa hasil fotosintesis?", b: "zat gula dan oksigen", s: ["air dan tanah", "karbon dioksida dan air", "pupuk dan oksigen"], pr: v => `Hasil fotosintesis adalah ${v}.`, sulit: true },
    ],
    ide: [{ b: "tumbuhan hijau membuat makanannya sendiri", s: ["makanan manusia", "warna hijau tumbuhan", "pohon di hutan"] },
      { b: "tempat dan bahan fotosintesis", s: ["akar di dalam tanah", "karbon dioksida di udara", "zat hijau daun"] },
      { b: "hasil fotosintesis dan manfaatnya", s: ["oksigen yang kita hirup", "zat gula pada buah", "kehidupan di laut"] }],
    jd: ["Merawat Bunga di Taman", "Manfaat Sinar Matahari bagi Kulit", "Memasak Sayur Bayam"],
    simpul: { b: "Tumbuhan membuat makanannya sendiri dan menghasilkan oksigen yang dibutuhkan makhluk hidup.", s: ["Tumbuhan mengambil makanan dari hewan.", "Fotosintesis terjadi di akar.", "Tumbuhan tidak membutuhkan cahaya matahari."] } },

  { judul: "Mengenal Jenis Sampah",
    para: [["Setiap hari, rumah kita menghasilkan sampah.", "Sampah dapat dibedakan menjadi dua jenis, yaitu sampah organik dan sampah anorganik."],
      ["Sampah organik berasal dari makhluk hidup, misalnya sisa makanan dan daun kering.", "Sampah ini mudah membusuk dan dapat diolah menjadi pupuk kompos.", "Sampah anorganik, misalnya plastik, kaleng, dan kaca, sulit terurai.", "Kantong plastik bahkan membutuhkan puluhan sampai ratusan tahun untuk terurai."],
      ["Kita dapat mengurangi sampah dengan cara 3R.", "3R adalah <i>reduce</i> (mengurangi), <i>reuse</i> (memakai kembali), dan <i>recycle</i> (mendaur ulang).", "Contohnya, membawa tas belanja sendiri dan memakai botol minum isi ulang."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Sampah dibedakan menjadi dua jenis, yaitu …", b: "sampah organik dan anorganik", s: ["sampah basah dan sampah bersih", "sampah besar dan sampah kecil", "sampah rumah dan sampah sekolah"], pr: v => `Sampah dibedakan menjadi ${v}.` },
      { p: 1, k: [1, 0], q: "Contoh sampah organik adalah …", b: "sisa makanan dan daun kering", s: ["plastik dan kaleng", "kaca dan besi", "botol dan sedotan"], pr: v => `Contoh sampah organik adalah ${v}.` },
      { p: 1, k: [1, 1], q: "Sampah organik dapat diolah menjadi …", b: "pupuk kompos", s: ["kantong plastik", "kaca baru", "bahan bakar mobil"], pr: v => `Sampah organik dapat diolah menjadi ${v}.` },
      { p: 1, k: [1, 3], q: "Berapa lama kantong plastik terurai?", b: "puluhan sampai ratusan tahun", s: ["dua minggu", "satu hari", "satu bulan"], pr: v => `Kantong plastik membutuhkan ${v} untuk terurai.`, sulit: true },
      { p: 2, k: [2, 1], q: "Arti <i>reuse</i> adalah …", b: "memakai kembali", s: ["mengurangi", "mendaur ulang", "membuang"], pr: v => `Arti <i>reuse</i> adalah ${v}.` },
      { p: 2, k: [2, 2], q: "Contoh cara mengurangi sampah menurut bacaan adalah …", b: "membawa tas belanja sendiri", s: ["membakar sampah plastik", "membuang sampah ke sungai", "memakai kantong plastik baru setiap hari"], pr: v => `Salah satu cara mengurangi sampah adalah ${v}.`, sulit: true },
    ],
    ide: [{ b: "dua jenis sampah", s: ["sampah di rumah", "sampah setiap hari", "tempat sampah"] },
      { b: "perbedaan sampah organik dan anorganik", s: ["kantong plastik", "pupuk kompos", "daun kering"] },
      { b: "cara mengurangi sampah dengan 3R", s: ["tas belanja", "botol minum", "bahasa Inggris"] }],
    jd: ["Membuat Kue dari Sisa Makanan", "Pergi ke Pasar", "Kebun Sayur di Rumah"],
    simpul: { b: "Sampah perlu dipilah dan dikurangi agar lingkungan tetap bersih.", s: ["Semua sampah cepat membusuk.", "Plastik adalah sampah organik.", "Sampah tidak perlu dipilah."] } },

  { judul: "Merawat Kesehatan Gigi",
    para: [["Gigi membantu kita mengunyah makanan.", "Gigi yang sehat membuat kita nyaman makan dan berbicara."],
      ["Agar sehat, gosoklah gigi paling sedikit dua kali sehari.", "Waktu yang tepat adalah pagi setelah sarapan dan malam sebelum tidur.", "Gosoklah gigi selama dua menit dengan gerakan pelan."],
      ["Makanan manis yang menempel di gigi dapat menyebabkan gigi berlubang.", "Karena itu, kurangi makan permen dan berkumurlah setelah makan.", "Periksakan juga gigimu ke dokter gigi setiap enam bulan sekali."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Apa fungsi gigi menurut bacaan?", b: "mengunyah makanan", s: ["mencium bau", "mendengar suara", "melihat benda"], pr: v => `Gigi membantu kita ${v}.` },
      { p: 1, k: [1, 0], q: "Paling sedikit berapa kali kita menggosok gigi dalam sehari?", b: "dua kali", s: ["satu kali", "lima kali", "sepuluh kali"], pr: v => `Kita perlu menggosok gigi paling sedikit ${v} sehari.` },
      { p: 1, k: [1, 1], q: "Kapan waktu yang tepat untuk menggosok gigi?", b: "pagi setelah sarapan dan malam sebelum tidur", s: ["siang sebelum makan dan sore setelah bermain", "pagi sebelum sarapan saja", "hanya ketika gigi terasa sakit"], pr: v => `Waktu yang tepat menggosok gigi adalah ${v}.`, sulit: true },
      { p: 1, k: [1, 2], q: "Berapa lama sebaiknya kita menggosok gigi?", b: "dua menit", s: ["sepuluh detik", "setengah jam", "sepuluh menit"], pr: v => `Kita sebaiknya menggosok gigi selama ${v}.` },
      { p: 2, k: [2, 0], q: "Apa yang dapat menyebabkan gigi berlubang?", b: "makanan manis yang menempel di gigi", s: ["minum air putih", "makan sayur", "berkumur setelah makan"], pr: v => `Gigi berlubang dapat disebabkan oleh ${v}.` },
      { p: 2, k: [2, 2], q: "Seberapa sering gigi perlu diperiksakan ke dokter gigi?", b: "setiap enam bulan sekali", s: ["setiap hari", "setiap minggu", "sepuluh tahun sekali"], pr: v => `Gigi perlu diperiksakan ke dokter gigi ${v}.`, sulit: true },
    ],
    ide: [{ b: "pentingnya gigi yang sehat", s: ["makanan yang dikunyah", "cara berbicara", "makan bersama keluarga"] },
      { b: "cara menggosok gigi yang benar", s: ["sarapan pagi", "gerakan pelan", "tidur malam"] },
      { b: "cara mencegah gigi berlubang", s: ["permen yang manis", "dokter gigi", "enam bulan"] }],
    jd: ["Permen Kesukaanku", "Sarapan Pagi yang Lezat", "Dokter Hewan di Desa"],
    simpul: { b: "Gigi tetap sehat jika rajin dirawat dan diperiksakan.", s: ["Makan permen sebanyak-banyaknya membuat gigi kuat.", "Gigi cukup digosok sekali seminggu.", "Gigi tidak perlu diperiksa ke dokter."] } },

  { judul: "Pesona Danau Toba",
    para: [["Danau Toba terletak di Provinsi Sumatra Utara.", "Danau ini adalah danau terbesar di Indonesia."],
      ["Danau Toba terbentuk dari letusan gunung api purba sekitar 74.000 tahun yang lalu.", "Letusan itu meninggalkan cekungan raksasa yang kemudian terisi air.", "Danau seperti ini disebut danau vulkanik."],
      ["Di tengah Danau Toba terdapat Pulau Samosir.", "Pulau ini didiami oleh masyarakat Batak.", "Di sana, wisatawan dapat melihat rumah adat Batak dan menonton tari tortor."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Danau Toba terletak di provinsi …", b: "Sumatra Utara", s: ["Sumatra Barat", "Aceh", "Riau"], pr: v => `Danau Toba terletak di Provinsi ${v}.` },
      { p: 0, k: [0, 1], q: "Menurut bacaan, Danau Toba adalah …", b: "danau terbesar di Indonesia", s: ["danau terdalam di dunia", "danau buatan terbesar", "danau terkecil di Sumatra"], pr: v => `Danau Toba adalah ${v}.` },
      { p: 1, k: [1, 0], q: "Danau Toba terbentuk dari …", b: "letusan gunung api purba", s: ["gempa bumi di laut", "hujan selama bertahun-tahun", "sungai yang dibendung"], pr: v => `Danau Toba terbentuk dari ${v}.` },
      { p: 1, k: [1, 0], q: "Kapan Danau Toba terbentuk?", b: "sekitar 74.000 tahun yang lalu", s: ["sekitar 740 tahun yang lalu", "sekitar 7.400 tahun yang lalu", "sekitar 740.000 tahun yang lalu"], pr: v => `Danau Toba terbentuk ${v}.`, sulit: true },
      { p: 1, k: [1, 2], q: "Danau yang terbentuk dari letusan gunung api disebut …", b: "danau vulkanik", s: ["danau buatan", "waduk", "rawa"], pr: v => `Danau yang terbentuk dari letusan gunung api disebut ${v}.` },
      { p: 2, k: [2, 0], q: "Pulau apa yang terdapat di tengah Danau Toba?", b: "Pulau Samosir", s: ["Pulau Nias", "Pulau Bangka", "Pulau Weh"], pr: v => `Di tengah Danau Toba terdapat ${v}.` },
      { p: 2, k: [2, 2], q: "Tari apa yang dapat ditonton wisatawan di Pulau Samosir?", b: "tari tortor", s: ["tari saman", "tari kecak", "tari jaipong"], pr: v => `Di Pulau Samosir, wisatawan dapat menonton ${v}.`, sulit: true },
    ],
    ide: [{ b: "letak Danau Toba sebagai danau terbesar di Indonesia", s: ["Provinsi Sumatra Utara", "danau-danau di Indonesia", "luas Pulau Sumatra"] },
      { b: "terbentuknya Danau Toba", s: ["cekungan raksasa", "74.000 tahun yang lalu", "air hujan"] },
      { b: "Pulau Samosir dan budaya Batak", s: ["rumah adat", "tari tortor", "para wisatawan"] }],
    jd: ["Mendaki Gunung Api", "Tari Kecak dari Bali", "Memancing di Sungai"],
    simpul: { b: "Danau Toba adalah danau vulkanik besar yang kaya akan budaya Batak.", s: ["Danau Toba terbentuk dari bendungan sungai.", "Danau Toba terletak di Pulau Jawa.", "Pulau Samosir terletak jauh dari Danau Toba."] } },

  { judul: "Rahasia Warna Pelangi",
    para: [["Pelangi adalah lengkungan warna-warni di langit.", "Pelangi biasanya muncul setelah hujan, saat matahari kembali bersinar."],
      ["Pelangi terjadi ketika cahaya matahari mengenai titik-titik air di udara.", "Titik-titik air itu membiaskan cahaya putih matahari dan menguraikannya menjadi beberapa warna.", "Warna pelangi ada tujuh, yaitu merah, jingga, kuning, hijau, biru, nila, dan ungu."],
      ["Untuk melihat pelangi, kita harus membelakangi matahari.", "Kita juga dapat membuat pelangi sendiri dengan menyemprotkan air ke udara pada pagi atau sore hari yang cerah."]],
    fakta: [
      { p: 0, k: [0, 1], q: "Kapan pelangi biasanya muncul?", b: "setelah hujan, saat matahari kembali bersinar", s: ["tengah malam saat bulan purnama", "ketika langit mendung tebal", "ketika hujan es turun"], pr: v => `Pelangi biasanya muncul ${v}.` },
      { p: 1, k: [1, 0], q: "Pelangi terjadi ketika cahaya matahari mengenai …", b: "titik-titik air di udara", s: ["daun-daun pohon", "debu di jalan", "permukaan tanah"], pr: v => `Pelangi terjadi ketika cahaya matahari mengenai ${v}.` },
      { p: 1, k: [1, 2], q: "Berapa jumlah warna pelangi?", b: "tujuh", s: ["lima", "enam", "sembilan"], pr: v => `Pelangi memiliki ${v} warna.` },
      { p: 1, k: [1, 2], q: "Warna pelangi yang terletak di antara biru dan ungu adalah …", b: "nila", s: ["hijau", "jingga", "kuning"], pr: v => `Warna di antara biru dan ungu adalah ${v}.`, sulit: true },
      { p: 2, k: [2, 0], q: "Agar dapat melihat pelangi, kita harus …", b: "membelakangi matahari", s: ["menghadap matahari", "memakai kacamata hitam", "berada di dalam rumah"], pr: v => `Agar dapat melihat pelangi, kita harus ${v}.`, sulit: true },
      { p: 2, k: [2, 1], q: "Bagaimana cara membuat pelangi sendiri?", b: "menyemprotkan air ke udara pada hari yang cerah", s: ["menyalakan lampu di kamar gelap", "mencampur cat warna-warni", "menyiram tanah pada malam hari"], pr: v => `Kita dapat membuat pelangi dengan ${v}.` },
    ],
    ide: [{ b: "pengertian pelangi dan waktu munculnya", s: ["hujan yang deras", "langit biru", "matahari pagi"] },
      { b: "proses terjadinya pelangi", s: ["cahaya putih matahari", "warna merah dan ungu", "titik-titik air"] },
      { b: "cara melihat dan membuat pelangi", s: ["semprotan air", "pagi hari yang cerah", "posisi matahari"] }],
    jd: ["Hujan di Sore Hari", "Cat Air Tujuh Warna", "Matahari Terbenam"],
    simpul: { b: "Pelangi terbentuk dari cahaya matahari yang diuraikan oleh titik-titik air.", s: ["Pelangi muncul pada tengah malam.", "Pelangi hanya berwarna merah.", "Pelangi terbentuk dari asap."] } },

  { judul: "Siaga Saat Gempa Bumi",
    para: [["Gempa bumi adalah getaran atau guncangan di permukaan bumi.", "Indonesia sering mengalami gempa karena terletak di pertemuan tiga lempeng bumi."],
      ["Jika gempa terjadi saat kamu di dalam ruangan, segera berlindung di bawah meja yang kuat.", "Lindungi kepalamu dengan tangan atau tas.", "Jauhi jendela kaca dan lemari yang mudah roboh."],
      ["Setelah guncangan berhenti, keluarlah dengan tertib menuju lapangan terbuka.", "Jangan berlari dan jangan berdesakan.", "Ikuti petunjuk guru atau petugas."]],
    fakta: [
      { p: 0, k: [0, 0], q: "Apa yang dimaksud dengan gempa bumi?", b: "getaran atau guncangan di permukaan bumi", s: ["angin kencang yang berputar", "naiknya air laut ke darat", "turunnya hujan deras"], pr: v => `Gempa bumi adalah ${v}.` },
      { p: 0, k: [0, 1], q: "Mengapa Indonesia sering mengalami gempa?", b: "Indonesia terletak di pertemuan tiga lempeng bumi", s: ["Indonesia memiliki banyak sungai", "Indonesia beriklim tropis", "Indonesia memiliki banyak hutan"], pr: v => `Indonesia sering mengalami gempa karena ${v}.`, sulit: true },
      { p: 1, k: [1, 0], q: "Saat gempa terjadi di dalam ruangan, kita harus berlindung …", b: "di bawah meja yang kuat", s: ["di dekat jendela kaca", "di samping lemari", "di atas kursi"], pr: v => `Saat gempa di dalam ruangan, kita berlindung ${v}.` },
      { p: 1, k: [1, 1], q: "Dengan apa kita melindungi kepala?", b: "tangan atau tas", s: ["buku tulis yang tipis", "kertas koran", "selimut basah"], pr: v => `Kita melindungi kepala dengan ${v}.` },
      { p: 1, k: [1, 2], q: "Benda yang harus dijauhi saat gempa adalah …", b: "jendela kaca dan lemari", s: ["meja yang kuat", "lapangan terbuka", "guru dan petugas"], pr: v => `Saat gempa, kita harus menjauhi ${v}.` },
      { p: 2, k: [2, 0], q: "Apa yang dilakukan setelah guncangan berhenti?", b: "keluar dengan tertib menuju lapangan terbuka", s: ["kembali duduk di kelas", "berlari secepatnya sambil berdesakan", "masuk ke dalam lemari"], pr: v => `Setelah guncangan berhenti, kita ${v}.`, sulit: true },
    ],
    ide: [{ b: "pengertian gempa dan penyebabnya di Indonesia", s: ["permukaan bumi", "tiga lempeng", "getaran kecil"] },
      { b: "cara berlindung saat gempa di dalam ruangan", s: ["meja yang kuat", "jendela kaca", "tas sekolah"] },
      { b: "yang dilakukan setelah guncangan berhenti", s: ["lapangan terbuka", "petunjuk guru", "berlari kencang"] }],
    jd: ["Bermain di Lapangan Terbuka", "Lemari Baru di Kelas", "Gunung Api di Indonesia"],
    simpul: { b: "Kita perlu mengetahui cara menyelamatkan diri saat gempa terjadi.", s: ["Saat gempa, kita sebaiknya berlari berdesakan.", "Gempa bumi tidak pernah terjadi di Indonesia.", "Saat gempa, kita sebaiknya berdiri di dekat jendela."] } },
];
